# Generated by Django 2.1.11 on 2019-11-19 05:38

import creditcards.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import django_localflavor_us.models
import languages.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=128, verbose_name='address')),
                ('city', models.CharField(default='College Station', max_length=64, verbose_name='city')),
                ('state', django_localflavor_us.models.USStateField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AS', 'American Samoa'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('AA', 'Armed Forces Americas'), ('AE', 'Armed Forces Europe'), ('AP', 'Armed Forces Pacific'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('GU', 'Guam'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('MP', 'Northern Mariana Islands'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('PR', 'Puerto Rico'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VI', 'Virgin Islands'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], default='TX', max_length=2, verbose_name='state')),
                ('zip_code', models.CharField(default='77840', max_length=5, verbose_name='zip code')),
                ('country', django_countries.fields.CountryField(default='US', max_length=2, verbose_name='country')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='latitude')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='longitude')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CareService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_pressure', models.BooleanField(default=False, verbose_name='measure blood pressure')),
                ('blood_sugar', models.BooleanField(default=False, verbose_name='measure blood sugar')),
                ('temperature', models.BooleanField(default=False, verbose_name='measure body temperature')),
                ('shower', models.BooleanField(default=False, verbose_name='help take a shower or tub bath')),
                ('hair_washing', models.BooleanField(default=False, verbose_name='help washing hair')),
                ('teeth_brushing', models.BooleanField(default=False, verbose_name='help brush teeth')),
                ('bed_bathing', models.BooleanField(verbose_name='help clean whole body with wet towel')),
                ('food_feeding', models.BooleanField(default=False, verbose_name='help feed food')),
                ('medicine_feeding', models.BooleanField(default=False, verbose_name='help feed medicine')),
                ('upper_limb_moving', models.BooleanField(default=False, verbose_name='help move upper limb')),
                ('lower_limb_moving', models.BooleanField(default=False, verbose_name='help move lower limb')),
                ('turn_over', models.BooleanField(default=False, verbose_name='help turn whole body over on bed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='phone number')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='F', max_length=1, verbose_name='gender')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='date of birth')),
                ('language', languages.fields.LanguageField(choices=[('zh', 'Chinese'), ('en', 'English'), ('es', 'Spanish')], default='en', max_length=3, verbose_name='preferred language')),
                ('is_taker', models.BooleanField(default=False, verbose_name='taker status')),
                ('is_provider', models.BooleanField(default=False, verbose_name='provider status')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicare', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=1, verbose_name='medicare')),
                ('medicaid', models.BooleanField(default=False, verbose_name='medicaid')),
                ('disabled', models.BooleanField(default=False, verbose_name='disabled in action')),
                ('chronic', models.BooleanField(default=False, verbose_name='chronic disease')),
                ('at_home_member', models.BooleanField(default=False, verbose_name='any family member at home')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', creditcards.models.CardNumberField(max_length=25, verbose_name='card number')),
                ('card_expiry', creditcards.models.CardExpiryField(verbose_name='expiration date')),
                ('card_code', creditcards.models.SecurityCodeField(max_length=4, verbose_name='security code')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
