# Generated by Django 2.1.11 on 2019-12-01 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalprofile',
            name='country',
            field=models.CharField(default='College Station', max_length=64, verbose_name='country'),
        ),
        migrations.AddField(
            model_name='generalprofile',
            name='email',
            field=models.CharField(default='College Station', max_length=64, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='generalprofile',
            name='firstName',
            field=models.CharField(default='College Station', max_length=64, verbose_name='firstName'),
        ),
        migrations.AddField(
            model_name='generalprofile',
            name='lastName',
            field=models.CharField(default='College Station', max_length=64, verbose_name='lastName'),
        ),
        migrations.AddField(
            model_name='generalprofile',
            name='phone',
            field=models.CharField(default='College Station', max_length=64, verbose_name='phone'),
        ),
        migrations.AddField(
            model_name='generalprofile',
            name='state',
            field=models.CharField(default='College Station', max_length=64, verbose_name='state'),
        ),
    ]
