# Generated by Django 2.1.11 on 2019-12-10 04:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import languages.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0002_auto_20191209_2243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', languages.fields.LanguageField(choices=[('zh', 'Chinese'), ('en', 'English'), ('es', 'Spanish')], default='en', max_length=3, verbose_name='language')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
