# Generated by Django 2.1.11 on 2019-12-10 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalprofile',
            name='language',
        ),
    ]
