# Generated by Django 2.1.11 on 2019-12-10 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_remove_generalprofile_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalprofile',
            name='image_url',
            field=models.TextField(blank=True, default='/static/images/avatars/avatar_10.png', verbose_name='image url'),
        ),
        migrations.AddField(
            model_name='generalprofile',
            name='num_of_comments',
            field=models.IntegerField(blank=True, default=204, verbose_name='number of comments'),
        ),
        migrations.AddField(
            model_name='generalprofile',
            name='rate',
            field=models.FloatField(blank=True, default=3.072030811573028, verbose_name='average rate'),
        ),
    ]
