# Generated by Django 2.1.11 on 2019-12-10 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20191209_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalprofile',
            name='image_url',
            field=models.TextField(blank=True, default='/static/images/avatars/avatar_5.png', verbose_name='image url'),
        ),
        migrations.AlterField(
            model_name='generalprofile',
            name='num_of_comments',
            field=models.IntegerField(blank=True, default=100, verbose_name='number of comments'),
        ),
        migrations.AlterField(
            model_name='generalprofile',
            name='rate',
            field=models.FloatField(blank=True, default=2.5, verbose_name='average rate'),
        ),
    ]
