# Generated by Django 2.1.11 on 2019-12-11 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20191210_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalprofile',
            name='is_taker',
            field=models.BooleanField(default=True, verbose_name='taker status'),
        ),
    ]
