# Generated by Django 2.1.11 on 2019-11-11 03:45

from django.db import migrations, models
import languages.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='at_home_member',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1, verbose_name='family member at home'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='chronic',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1, verbose_name='chronic disease'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='disable',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1, verbose_name='disable in action'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='language',
            field=languages.fields.LanguageField(choices=[('zh', 'Chinese'), ('en', 'English'), ('es', 'Spanish')], default='en', max_length=3, verbose_name='preferred language'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='medicaid',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1, verbose_name='medicaid'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='medicare',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=1, verbose_name='medicare'),
        ),
    ]
