# Generated by Django 2.1.11 on 2019-11-11 04:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191110_2145'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('T', 'Taker'), ('P', 'Provider')], default='T', max_length=1, verbose_name='which role registers services')),
                ('blood_pressure', models.BooleanField(default=False, verbose_name='measure blood pressure')),
                ('blood_test', models.BooleanField(default=False, verbose_name='draw blood for testing')),
                ('blood_sugar', models.BooleanField(default=False, verbose_name='measure blood sugar')),
                ('temperature', models.BooleanField(default=False, verbose_name='measure body temperature')),
                ('medicine_deliver', models.BooleanField(default=False, verbose_name='pick medicine and deliver')),
                ('meal_deliver', models.BooleanField(default=False, verbose_name='deliver nutritious meals')),
                ('feeding', models.BooleanField(default=False, verbose_name='help feeding')),
                ('washing', models.BooleanField(default=False, verbose_name='help washing body')),
                ('accompany_clinic', models.BooleanField(default=False, verbose_name='accompany people to clinic visit')),
                ('limb_exercise', models.BooleanField(default=False, verbose_name='help limbs exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
