# Generated by Django 2.1.11 on 2019-12-09 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='service time')),
                ('note', models.TextField(verbose_name='note')),
                ('provider_feedback', models.TextField(verbose_name='provider feedback')),
                ('taker_feedback', models.TextField(verbose_name='taker feedback')),
                ('star', models.IntegerField(verbose_name='star')),
                ('status', models.IntegerField(default=0, verbose_name='status')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider', to=settings.AUTH_USER_MODEL)),
                ('taker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taker', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CareService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='care service name')),
                ('price', models.IntegerField(verbose_name='price')),
                ('checked', models.BooleanField(verbose_name='checked')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carecases.CareCase')),
            ],
        ),
    ]
